export * from './user/entry'
export * from './business/entry'
export * from './service/entry'
export * from './working-hours/entry'
export * from './break/entry'
export * from './timeoff/entry'
export * from './common/entry'
export * from './onboarding/entry'

export type DomainEntityName =
  | 'User'
  | 'Business'
  | 'Service'
  | 'WorkingHours'
  | 'Break'
  | 'TimeOff'
