services:
  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
      args:
        - PUBLIC_TEST_VAR=afaqtest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
